language: python
install: true
script: true
deploy:
  - provider: elasticbeanstalk
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    region: "us-east-1"
    app: "homepage"
    env: "Homepage-env"
    bucket_name: "brianyu"
    on:
      branch: "master"
notifications:
  email:
    on_success: never
    on_failure: always
