services:
  web:
    build: .
    container_name: homepage_web
    environment:
      APPLICATION_ENV: dev
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - .:/home/app
version: "3.6"
